server:
  port: 8083


spring:
    datasource:
      url: jdbc:mysql://localhost:3306/microservices
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    application:
      name: USER-SERVICE


    jpa:
     database-platform: org.hibernate.dialect.MySQL8Dialect
     generate-ddl: true
     hibernate:
       ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
